# Experiment No. 8

# Tools for EDA-Study of Numpy Library

## Name - Krishiv Sharma
## PRN - 25070123065
## Batch - ENTC-A3
## Date - 18-02-26

In [3]:
#Declaration of Numpy
import numpy as np

a = np.array([50 , 60, 70, 80])
b = np.array([[7, 8, 9], [1, 2, 3]])
print(a)
print(b)

[50 60 70 80]
[[7 8 9]
 [1 2 3]]


In [4]:
# Dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
b.shape

(2, 3)

In [6]:
a.shape

(4,)

In [7]:
a.dtype

dtype('int64')

In [8]:
b.dtype

dtype('int64')

In [10]:
# In-Built functions using Numpy
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(2,11,3)

array([2, 5, 8])

In [17]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [21]:
print(b * 5)
print(a + 10)

[[35 40 45]
 [ 5 10 15]]
[60 70 80 90]


In [23]:
np.mean(a)


np.float64(65.0)

In [24]:
np.mean(b)

np.float64(5.0)

In [25]:
np.median(a)

np.float64(65.0)

In [26]:
np.median(b)

np.float64(5.0)

In [27]:
np.max(a)

np.int64(80)

In [28]:
np.max(b)

np.int64(9)

In [29]:
np.min(a)

np.int64(50)

In [31]:
np.min(b)

np.int64(1)

In [32]:
np.sum(a)

np.int64(260)

In [33]:
np.sum(b)

np.int64(30)